---
title: "PCA-cluster"
author: "eNVy"
date: "6/17/2021"
output: "github_document"
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "./")
here::i_am("Code/pca.rmd")
library(here)
here()
```

```{r, message=F, warning=F}
library(tidyverse)
library(tidymodels)
library(ggbiplot)
# devtools::install_github("vqv/ggbiplot")
```



Source the full function to read the df
```{r}
source(here("Code/generateInterpolatedDF.R"))
```

```{r, message=F, warning=F}
df_raw <- read_csv(here("Data/UCI_handWritten/data.csv"))

df_raw %>% head()
```

```{r}
df <- mostLameFuncEver(df = df_raw, n_int = 100) %>% 
  secondMostLameFuncEver()
df %>% head()
```

# PCA 

## This attempt is only for letters 'a' and 'b'

```{r}
df %>% 
  filter(char %in% c('a', 'b')) %>% 
  select(-key) -> df_init
```

<!-- func here to split the dataset and append as rows -->

```{r}
# tidy this

df_init %<>% 
  mutate(
    char2 = char
  ) %>% 
  relocate(char2, .before = "x2_1")

df_init[, c(1:201)] %>% 
  bind_rows(df_init[, c(202:402)] %>% 
              rename_with(~sub("2", "1", .x), 
                          .cols = !char2) %>% 
              rename(char = char2)) -> df_splitBind
```

```{r}
df_splitBind %>% 
  arrange(char) %>% 
  head()
```


```{r}
# since we're only epxrimenting with x coords
df_splitBind %>% 
  arrange(char) %>% 
  select(starts_with("x")) %>%
  # select(-all_of(c("char", "key"))) %>% .[c(1:2), ] %>% 
  prcomp() -> pca
```

# Cluster

Check if new PCA elements are clustered according to letter.

```{r}
pca %>% 
  ggbiplot(choices = c(1, 2), 
            ellipse = T, # labels = rownames(df_splitBind %>% select(-"char")), 
           groups = c(rep("a", 120), rep("b", 120)), 
           var.axes = F)
```

<!--  
```{r}
df_pca <- pca$rotation
df_pca %>% 
  kmeans(centers = 2) -> kmeans
```

# Visualize

```{r}
require(ggfortify)

df_pca %>% 
  bind_cols(cluster = kmeans$cluster, 
            axis = rownames(df_pca)) %>% 
  mutate(
    axis = str_detect(axis, "x"), 
    axis = case_when(axis ~ "x", !axis ~ "y"), 
    cluster = as.factor(cluster)
  ) %>% 
  ggplot() + 
  geom_point(aes(PC1, PC2, color = cluster, # color by the cluster
                 shape = axis),  # shape by the coordinate x or y
             alpha = 0.6, size = 2)
 
  
```
-->

# Conclusion:

Letters can be somewhat separated by using only 2 PCA components, which has ~80% variance explainability. 
